<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

class Neighborhood_generator extends CI_Controller {

    public function index() {
        

        
        
        
        $replace_string = <<<EOD
	SANTA ANA
	CAPOTILLO, ENS.
	EL DORAL
	ORTEGA, URB.
	BRISAS DE LAS PRADERAS, URB.
	EMER, RES.
	SAN FRANCISCO (CENTRO URBANO)
	PASEO DEL RIO, URB
	TERRANOVA, URB.
	OASIS,URB.
	EL BOLSILLO
	AZUL
	LAS FLORES
	SANTA ANA, BO.
	EL CAPACITO
	JOBO BONITO
	HERMANAS MIRABAL
	SANTA ANA, URB.
	PUEBLO NUEVO (SFM)
	SAN VICENTE, BO.
	LOS PLANITOS, BO.
	VILLAS PALMERAS RES.
	PUERTO RICO (SFM)
	BUENOS AIRES (EL ASILO)
	LA MANICERA
	RIVERA DEL JAYA
	VENTURA CRULLON I
	VENTURA GRULLON II
	FRANK GRULLON, URB. (VILLA VERDE)
	SAN GERONIMO
	SAN PEDRO
	VISTA DE SAN FRANCISCO
	EST LAS COLINAS, URB.
	EL HORMIGUERO
	HOLGUIN MARTE
	TAHINA
	SANTA LUISA
	CALLEJON CASTILLO
	LOS JIBARITOS
	LOS CHIRIPOS
	DUARTE ARRIBA
	VILLA DUARTE
	MADRIGAL
	DUARTE, ENS.
	ERCILIA PEPIN
	ALTO DE LA JAVIELA
	ABREU, URB. (SFM)
	ABREU II, URB.
	JENIFFER, URB.
	CAAMAÑO DEÑO, BO.
	VILLA OLIMPICA 1-ETAPA
	VILLA OLIMPICA 2-ETAPA
	TORIBIO PIANTINI, URB. 1-ETAPA
	TORIBIO PIANTINI 2-ETAPA
	TORIBIO PIANTINI 3-ETAPA
	PROYECTO INDUSTRIAL
	ESTADIO JULIAN JAVIER
	TORIBIO CAMILO, URB.
	TORIBIO CAMILO 2-ETAPA
	Toribio Camilo III
	CARMEN AÑIL BONO, URB
	SAN MARTIN
	LA CASTELLANA, URB.
	LORA, URB.
	SAN FRANCISCO, URB.
	LOS MAESTROS, URB. 1-ETAPA
	LOS MAESTROS, URB. 2-ETAPA
	LOS MAESTROS, URB. 3-ETAPA
	LOS MAESTROS, URB. 4-ETAPA
	VIA FERREA
	FELIX TAVERAS, URB.
	FELIX TAVERAS, URB. (ATRAS)
	LOS RIELES, PROYECTO HAB.
	VALLE VERDE, URB. (P. PIÑA, URB)
	AVENIDA LOS RIELES
	LAS PALMAS, URB.
	ESPINAL, URB.
	PINAR DEL JAYA, URB.
	PIÑA, URB. 1RA. ETAPA
	PIÑA, URB. 2DA. ETAPA
	PIÑA, URB. 3RA. ETAPA
	PERALTA BRACHE, URB. 4-ETAPA
	EL TEJAR, URB.
	DR FERNANDEZ, URB.
	PROYECTO THERMO SANCHEZ
	ANDUJAR, URB.
	EL SILENCIO, URB. 1RA. ETAPA
	EL SILENCIO, URB. 2DA. ETAPA
	EL SILENCIO, URB. 3RA. ETAPA
	LA FORTUNA, URB. (San Frco. De Macoris)
	CAPERUZA, URB. 1RA. ETAPA
	CAPERUZA, URB. 2DA. ETAPA
	CAPERUZA, URB.
	ANA SALIME, URB.
	BRUGAL, URB. 1RA. ETAPA
	BRUGAL, URB. 2DA. ETAPA
	BRUGAL III, URB.
	CAMPOS FERNANDEZ, URB.
	CAMPOS FERNANDEZ II, URB.
	EL LAUREL, URB.
	DON MARIO, URB.
	GARCIA NUÑEZ, URB.
	MIRADOR DEL JAYA, URB.
	NEFTALY I, URB.
	NEFTALY II, URB.
	NEFTALY III,URB
	JARDINES DE LAS PRADERAS
	ZONA FRANCA
	ENSUEÑO, RES.
	ALVAREZ, URB.
	ALMANZAR, URB.
	BAELIN, RES.
	CAONABO, URB. 1RA. ETAPA
	CAONABO, URB. 2DA. ETAPA
	LOS CIRUELOS, URB.
	WILLIAM MIESES, ENS.
	GETSEMANI
	CACERES, URB.
	GISOLIS, URB.
	VISTA DEL VALLE, RES
	VISTA DEL VALLE
	GREGORIO LUPERON
	CAMINO AL MEDIO
	LOS CIRUELOS, PROYECTO HAB.
	EL CIRUELILLO, PROYECTO HAB.
	NUEVO SAN FRANCISCO, URB.
	LOS PALMARES, URB.
	LUNES, URB.
	PRIMAVERAL, URB.
	LAS COLINAS, ENS.
	HAMLET,URB.
	CARRETERA MADERA
	ESPINOLA
	OLIMPIA, RES.
	FERNANDEZ, URB.
	PARAGUON, URB.
	VISTA BELLA, URB.
	EL GALLINERO
	SAN FRANCISCO DE ASIS
	WEBER, ENS.
	AGUILA, ENS.
	EL CIRUELILLO
	VERAS DEL JAYA, URB.
	EL CIRUELILLO, RESPALDO
	VILLA PALMA
	RIVERA DEL JAYA, URB.
	UGAMBA
	LOS JARDINES, BO.
	LOS DESESPERADOS
	24 DE ABRIL
	LA ALTAGRACIA
	INVI, BO.
	CRISTO REY
	CUESTA BLANCA
	LA PIÑITA
	FELIX, URB
	FELIX II, URB.
	SALVADOR THEN (EL SORDO)
	LA CENIZA (SFM)
	RINCON BONO
	CAMINO VECINAL
	ABREU, ENS. (SFM)
	LAS COLINAS I, URB.
	LAS COLINAS II, URB.
	PICO DE LA COTORRA
	EL DORADO, RES.
	EL RINCON DE SAN FRANCISCO
	COLON, SECCION
	LA BOCA
	LA BOCA (RURAL)
	CAÑO SECO
	CAÑO SECO (RURAL)
	LA GUAMA
	LA GUAMA (RURAL)
	LOS RIELES ABAJO
	LOS RIELES ABAJO (RURAL)
	COLON
	COLON (RURAL)
	EL BARRO
	EL BOBO (SEC. COLON)
	EL BOBO (SEC. COLON, RURAL)
	MAL HOMBRE
	EL QUEMADO (SEC. COLON)
	EL CAIMITO
	BANDERA
	CAMU
	LA JINA (SEC. COLON)
	LA ENEA (SEC. COLON)
	LAS CEJAS
	LAS CEJAS (RURAL)
	MIRABEL
	MIRABEL (RURAL)
	CRUCE DE MIRABEL
	CRUCE DE MIRABEL (RURAL)
	EL HATO (SEC. COLON)
	EL HATO (SEC. COLON, RURAL)
	EL TRES
	REVENTACION
	LA SEQUIA
	BIJAO (SEC. COLON)
	BIJAO (SEC. COLON, RURAL)
	SABANA SAN DIEGO
	MOJIN
	MOJIN (RURAL)
	RANCHO ARRIBA (SEC. COLON)
	RANCHO ARRIBA (RURAL)
	LOS ANCONES
	LOS ANCONES (RURAL)
	SAN DIEGO
	SAN DIEGO (RURAL)
	NONA
	NONA (RURAL)
	HATILLO (SEC. COLON)
	HATILLO (RURAL)
	CRUCE DEL CAIMITO
	CRUCE DEL CAIMITO (RURAL)
	NAZA DE HATILLO
	NAZA DE HATILLO (RURAL)
	GUZMAN
	GUZMAN (RURAL)
	LA YAGUIZA (SEC. COLON)
	LA YAGUIZA (RURAL)
	RIELES, BO.
	BANDERA (RURAL)
	VISTA HERMOSA,URB.
	CRUZ DE CENOVI, SECCION
	LOS CACAOS (SEC. CRUZ DE CENOVI)
	LOS CACAOS (RURAL, CRUZ DE CENOVI)
	LA YAGUIZA ABAJO (SEC. CRUZ DE CENOVI)
	LA YAGUIZA ABAJO (RURAL)
	PORQUERO ABAJO
	PORQUERO ABAJO (RURAL)
	HATICO
	HATICO (RURAL)
	PORQUERO ARRIBA
	PORQUERO ARRIBA (RURAL)
	EL GAJO
	EL GAJO (RURAL)
	EL MAMEY
	EL MAMEY (RURAL)
	LA NAZA
	LA NAZA (RURAL)
	LA CRUZ DE CENOVI
	LA CRUZ DE CENOVI (RURAL)
	LA COLONIA
	LA COLONIA (RURAL)
	LA ROSA
	LA ROSA (RURAL)
	LOS INDIOS DE CENOVI
	LOS INDIOS DE CENOVI (RURAL)
	HOYO VIEJO
	HOYO VIEJO (RURAL)
	EL CANAL
	EL CANAL (RURAL)
	LA BOMBA DE CENOVI
	LA BOMBA DE CENOVI (RURAL)
	LAS CAOBAS (SEC. CRUZ DE CENOVI)
	EL BOBO (SEC. CRUZ DE CENOVI)
	EL BOBO (SEC. CRUZ DE CENOVI, RURAL)
	LA MARGA (SEC. CRUZ DE CENOVI)
	LA MARGA (RURAL, SEC. CRUZ DE CENOVI)
	SABANA DEL REY ARRIBA
	SABANA DEL REY ARRIBA (RURAL)
	LOS INDIOS DE CENOVI
	LOS INDIOS DE CENOVI (RURAL)
	LOS ARROYOS (SEC. CRUZ DE CENOVI)
	DEMAJAGUAL, SECCION (LOMA)
	DEMAJAGUAL ARRIBA
	DEMAJAGUAL ARRIBA (RURAL)
	DEMAJAGUAL ABAJO
	DEMAJAGUAL ABAJO (RURAL)
	LA VEREDA DEL DEMAJAGUAL
	LA VEREDA DEL DEMAJAGUAL (RURAL)
	PALMARITO
	PALMARITO (RURAL)
	EL LLANO
	EL LLANO (RURAL)
	LA GAZA
	LOS PONTONES
	LOS PONTONES (RURAL)
	PATAO
	PATAO (RURAL)
	LOMA DE AMACEY
	LOMA DE AMACEY (RURAL)
	LA CABUYA
	LA CABUYA (RURAL)
	HATILLO (SEC. DEMAJAGUAL)
	PIE DE PLATA (SEC. DEMAJAGUAL)
	PIE DE PLATA (RURAL, DEMAJAGUAL)
	EL CALABOZO
	DICHOSO ARRIBA
	DICHOSO ABAJO
	LOS PELADEROS
	LOS RINCONES
	LOS BARROS
	LA VEREDA DE DICHOSO
	RAMONAL ARRIBA
	LA PALOMA
	LOS LIRIOS
	RAMONAL ABAJO
	LA CIENAGA
	LA CIENAGA (RURAL)
	LOS ESPINOS (SEC. DEMAJAGUAL)
	LOS ESPINOS (RURAL, DEMAJAGUAL))
	LA CHANCLETA (SEC. DEMAJAGUAL)
	LA CHANCLETA (RURAL, SEC. DEMAJAGUAL)
	POZO DEL JOBO (SEC. DEMAJAGUAL)
	POZO DEL JOBO (RURAL)
	GUIZA LA PENDA, SECCION (LLANO)
	FACTOR
	FACTOR (RURAL)
	TUBAGUA
	TUBAGUA (RURAL)
	SANTA LUCIA
	SANTA LUCIA (RURAL)
	HONDURAS (SEC. GUIZA LA PENDA)
	HONDURAS (RURAL, GUIZA LA PENDA)
	GUIZA
	GUIZA (RURAL)
	ESTANZUELA ABAJO (LOMA)
	ESTANZUELA ABAJO (LOMA) (RURAL)
	LA PIEDRA
	LA PIEDRA (RURAL)
	ESTANZUELA ARRIBA
	ESTANZUELA ARRIBA (RURAL)
	LOS CERROS
	LOS CERROS (RURAL)
	LLAVE (LLANO)
	LLAVE (LLANO) (RURAL)
	SERRANO
	SERRANO (RURAL)
	GENIMO
	GENIMO (RURAL)
	LA GINA (SEC. GUIZA LA PENDA)
	LA GINA (RURAL, GUIZA LA PENDA)
	LA LIMA (SEC. GUIZA LA PENDA)
	LA LIMA (RURAL, GUIZA LA PENDA)
	GENIMILLO
	GENIMILLO (RURAL)
	HIGUERO
	EL POZO
	EL POZO (RURAL)
	LA JAYA SECCION
	LA JAYA-HOYO DE JAYA (LOMA)
	LA JAYA-HOYO DE JAYA (LOMA) (RURAL)
	SANTA ELENA
	SANTA ELENA (RURAL)
	MAIMORO
	MAIMORO (RURAL)
	LA CIDRA
	LA CIDRA (RURAL)
	LA YABACOA
	LOMA DE JAYA
	LA HIGUERETA
	FIRME DE LA BRISA
	LA CEIBA
	LA GUAMITA
	EL ARROYASO
	EL JOBITO
	LA MALEZA
	HONDO VALLE
	TRES PIES
	LA YAYA
	MARTEL
	EL POMITO
	EL LIMON (SEC. LA JAYA)
	LOS GANCHOS DE JAYA
	EL DERRUMBAO
	EL POMO
	LA JAGUITA (SEC. LA JAYA)
	NARANJO DULCE ARRIBA
	PANTIGOSO
	LOMA DE PERRO
	RANCHO ARRIBA (SEC. LA JAYA)
	RANCHO ABAJO
	ALTO DEL RAYO
	SONADOR
	LA PEGAJOSA
	LOS BASILIOS
	ALTO DE CABALLO
	LA MALENA DE JAYA
	LA LOMASA
	MATA VIEJA
	FIRME DE LOS ORTEGA
	NARANJO DULCE ABAJO
	LAGUNA DE COTO, SECCION
	GUAZARITA
	LAGUNA ARRIBA
	LOS PALOS
	COTO ARRIBA
	RINCON DE COTO
	COTO ABAJO
	LAGUNA AL MEDIO
	LAGUNA ABAJO
	LA BAJADA
	EL CARACOL
	RIO ARRIBA
	LOS LIMONES (SEC. LAGUNA DE COTO)
	BRAZO GRANDE
	EL BURRO
	PALO VERDE
	LOS PONTONES ABAJO
	BOBA
	EL SITIO
	EL INGENIO
	LA CENIZA (SEC. LAGUNA DE COTO)
	LOS CAIMITICOS
	CHINGUELO
	LOS GUAYUYOS
	LOS POMOS
	EL CATEY
	PALMARITO EL LIMON
	PALMARITO ABAJO
	LAGUNA DE COTO
	PIEDRA BLANCA
	LOS MATES
	LOS PONTONES ARRIBA
	NAGUA ARRIBA
	LA JOYA, SECCION (LLANO)
	EL ESPINO
	EL ESPINO (RURAL)
	BIJAO (SEC. LA JOYA)
	BIJAO (SEC. LA JOYA, RURAL)
	LA LIMA (SEC. LA JOYA)
	LA LIMA (RURAL, LA JOYA)
	LOS CADILLOS
	LOS CADILLOS (RURAL)
	JAIQUI
	JAIQUI (RURAL)
	LA LAGUNA (SEC. LA JOYA)
	LA LAGUNA (RURAL, LA JOYA)
	ARBOLINES
	ARBOLINES (RURAL)
	LA JOYA ARRIBA
	LA JOYA ARRIBA (RURAL)
	CABIRMA (LOMA)
	CABIRMA (LOMA) (RURAL)
	CASA DE ALTO (SEC. LA JOYA)
	CASA DE ALTO (SEC. LA JOYA, RURAL)
	RIO FRIO
	RIO FRIO (RURAL)
	LA JOYA (LLANO)
	LA JOYA (LLANO) (RURAL)
	LA GUAZUMITA
	LA GUAZUMITA (RURAL)
	LOS LIONES (LOMA)
	LOS LIONES (LOMA) (RURAL)
	EL CIGUAL
	EL CIGUAL (RURAL)
	HOYO GRANDE
	HOYO GRANDE (RURAL)
	LA LOMITA (SEC. LA JOYA)
	LA LOMITA (RURAL)
	LOMA DE LA JOYA
	LOMA DE LA JOYA (RURAL)
	LOMA DE LOS PAULINOS
	LOMA DE LOS PAULINOS (RURAL)
	EL MATE
	EL MATE (RURAL)
	RIO JAGUA (LLANO)
	RIO JAGUA (LLANO) (RURAL)
	LAS PAJAS
	LAS PAJAS (RURAL)
	LOS BEJUCOS, SECCION
	RANCHO ARRIBA (CORRAL LLANO)
	RANCHO ARRIBA (CORRAL LLANO) (RURAL)
	EL JIGUERO
	EL JIGUERO (RURAL)
	EL CERCADO ( LA LILA)
	EL CERCADO ( LA LILA) (RURAL)
	CASA DE ALTO (SEC. LOS BEJUCOS, LOMA)
	CASA DE ALTO (SEC. LOS BEJUCOS, LOMA RURAL)
	EL PIOJILLO (LLANO)
	EL PIOJILLO (LLANO) (RURAL)
	LA SABANA (SEC. LOS BEJUCOS)
	LA SABANA (RURAL, LOS BEJUCOS)
	EL GRILLO
	EL GRILLO (RURAL)
	LA PIRAGUA
	LA PIRAGUA (RURAL)
	LA PALMA
	LA PALMA (RURAL)
	LA LOMITA (LOMA, SEC. LOS BEJUCOS)
	LA LOMITA (LOMA, LOS BEJUCOS, RURAL)
	LOMA DEL MUERTO
	EL AGUACATE (SEC. LOS BEJUCOS)
	PALMA HERRADA
	LOS FARALLONES
	LOMA DE AGUA
	TUMBA BURROS (LLANO)
	TUMBA BURROS (LLANO) (RURAL)
	ESLABONES (LOMA)
	SANTA FE (LLANO)
	SANTA FE (LLANO) (RURAL)
	LA LOMITA (LOMA)
	LA LOMITA (LOMA) (RURAL)
	EL CONCRETO (HIDALGOS) (LLANO)
	EL CONCRETO (HIDALGOS) (LLANO) (RURAL)
	LOS CACAOS (SEC. LOS BEJUCOS)
	LOS CACAOS (RURAL, LOS BEJUCOS)
	LA ZOLAPA
	LA ZOLAPA (RURAL)
	EL NISPERO
	EL NISPERO (RURAL)
	LA JAIBA (LOMA)
	LOS ALGODONES (LLANO)
	LOS ALGODONES (LLANO) (RURAL)
	LOS BEJUCOS
	LOS BEJUCOS (RURAL)
	LA YAGUIZA (SEC. LOS BEJUCOS)
	LA YAGUIZA (RURAL)
	LA YAGUIZA ABAJO (SEC. LOS BEJUCOS)
	LA YAGUIZA ABAJO (RURAL)
	LA YAGUIZA CENTRAL
	LA YAGUIZA CENTRAL (RURAL)
	LAS GUAZUMAS, SECCION
	LA ERMITA (LLANO)
	LA ERMITA (LLANO) (RURAL)
	LOS JIBARITOS
	LOS JIBARITOS (RURAL)
	LAS GUAZUMAS
	LAS GUAZUMAS (RURAL)
	EL AGUACATE AFUERA (LOMA)
	EL AGUACATE AFUERA (LOMA) (RURAL)
	EL AGUACATE ADENTRO
	EL AGUACATE ADENTRO (RURAL)
	LA CAOBA (LLANO)
	LA CAOBA (LLANO) (RURAL)
	LA PIÑA
	LA PIÑA (RURAL)
	JARAGUA
	JARAGUA (RURAL)
	LA MADEJA
	LA MADEJA (RURAL)
	LOS ARROYOS (SEC. LAS GUAZUMAS)
	LOS ARROYOS (RURAL)
	LA LAGUNA (SEC. LA GUAZUMA)
	LA LAGUNA (RURAL, LA GUAZUMA)
	LOMA DE LOS BONILLA (LOMA)
	LOMA DE LOS BONILLA (LOMA) (RURAL)
	MENDEZ,URB.
	LA MALENA, SECCION
	CIGUAL (LOMA)
	CIGUAL (LOMA) (RURAL)
	LA MALENA
	CEIBITA
	ZUMBADORA
	LA BESTIA DE LA MALENA
	ARROYAZO
	LA TROCHA
	LA AUYAMA
	CUESTA BOBA
	CUESTA BOBA (RURAL)
	ARROYO BONITO
	ARROYO BONITO (RURAL)
	CATEY
	CRUCE DE LA MALENA
	CRUCE DE LA MALENA (RURAL)
	ATABALERO ABAJO (LOMA)
	ALTOS DE LOS NARANJOS
	ATABALEROS
	LA BESTIA DE ATABALERO
	CANETE
	CRUCE DE LOS BETANCES
	LUCAS
	AGUACATE
	GAJO MALO
	GAJO LA YUCA
	JURUNGO
	EL GUINEAL
	LOS CINCOS
	LA VEREDA
	VENUS
	LAS SABINAS
	LOS PALITOS
	LA CULATA (SEC. LA MALENA)
	SANTA FE (LOMAS)
	GUABINA
	ATABALERO ARRIBA
	BLANCO
	RANCHO ABAJO (SEC. LA MALENA)
	LA MANACLA
	ALTO DE LOPEZ
	LA CIGUA
	ARROYO EL TORO
	LOS FRANCESES
	PARAJE 41
	LA MALENITA
	LA MESA, SECCION
	LA MESA
	LA MESA (RURAL)
	CLAVICAL O CHABICAL
	CLAVICAL O CHABICAL (RURAL)
	CALLEJON DE LOS MAJIAS
	CALLEJON DE LOS MAJIAS (RURAL)
	CHUCHO VASQUEZ (LLANO)
	CHUCHO VASQUEZ (LLANO) (RURAL)
	HATO GRANDE
	HATO GRANDE (RURAL)
	MATA LARGA
	MATA LARGA (RURAL)
	LOMA AL MEDIO (LOMA)
	LOMA AL MEDIO (LOMA) (RURAL)
	EL LIMON (SEC. LA MESA)
	EL LIMON (SEC. LA MESA, RURAL)
	EL COROZO
	EL COROZO (RURAL)
	LA PEÑA, SECCION
	ALTO DEL PILON
	AZLOR
	AZLOR (RURAL)
	LOS BOTAOS
	LOS BRACITOS
	BUENOS AIRES
	CADILLAR
	CASA VIEJA (LLANO)
	CASA VIEJA (LLANO) (RURAL)
	EL CATEY (LOMA)
	EL CERCADO
	EL CERCADO (RURAL)
	CUABA
	ALTO O HATO DE CUEVAS
	CUEVAS
	CUABA ARRIBA
	HERRERA DE CUABA
	EL JAMO
	LA LAGUNETA
	QUEMAO
	EL MANGO
	MONTE BONITO
	LOS NARANJOS (SEC. LA PEÑA)
	LA PEÑA (LLANO)
	LA PEÑA (LLANO) (RURAL)
	POZO DEL JOBO (LOMA, SEC. LA PEÑA)
	LA REPRESA
	RINCON DEL HIGUERO
	TABIQUE O TANIQUE (TANQUE)
	EL VALLE
	LA ZARZA (SEC. LA PEÑA)
	LIMON DULCE
	DON RAMON
	LA AMARGURA
	LA CHANCLETA (SEC. LA PEÑA)
	EL QUEMAO (LA PEÑA)
	LOS CAÑOS
	LOS PLACERES
	LAS YERBAS
	LOS PUENTES
	PIE DE PLATA (SEC. LA PEÑA)
	EL LORO
	LA POCILGA
	MONTE NEGRO
	MONTE NEGRO (RURAL)
	PONTON
	PONTON (RURAL)
	LOS GUINEOS
	LA PEÑA,URB.
	LA SABANA (RURAL)
	ARENOSO, MUNICIPIO
	ARENOSO (CENTRO DEL PUEBLO)
	LOS ESTUDIANTES
	LAS MARIAS, URB.
	EL PALMAR
	PLAN DE URBANIZACIÓN
	PALMA SOLA O MONO SUCIO
	LA CANTERA
	EL AGUACATE, SECCION
	YABACOA (LOMA)
	LOS PLATANITOS (LLANO)
	EL AGUACATE (SEC. EL AGUACATE)
	LAS MATAS
	LOS ARTILES
	CIENAGA VIEJA
	LOS MAYABOS (LOMA)
	SABANETA
	BOCA DE PAYABO
	CUBA
	LAS COLES, SECCION
	LA RAYA
	LAS COLES
	CRUCE DE LA CABIRMA
	LAS GARZAS
	EL JOBO
	LAS CARRERAS, SECCION
	LAS CARRERAS
	LAS CARRERAS (RURAL)
	LOS CACAOS (SEC. LAS CARRERAS)
	RINCON BEBEDERO (SEC. LAS CARRERAS)
	LA JAGUA, SECCION
	EL GUAYABO
	LA JAGUA
	LA JAGUA (RURAL)
	RINCON BEBEDERO (SEC. LA JAGUA)
	VILLA MARIA
	LA GUAMA
	CASTILLO, MUNICIPIO (CENTRO)
	NUESTRA SRA DEL CARMEN
	NUEVO CASTILLO, BO.
	NUEVO CASTILLO, PROYECTO HAB.
	CARRETERA DUARTE
	CASTILLO, CENTRO DEL PUEBLO
	SAN ANTONIO ARRIBA
	LOS COCOS, BO.
	SUR, BARRIO (LA CANCHA)
	LA MANTECA
	CASTILLO, CENTRO DEL PUEBLO
	PUERTO RICO (CASTILLO)
	RABO DE CHIVO
	EL HOSPITAL
	EL PLAY (CASTILLO)
	GINA CLARA, SECCION
	FIRME DE GINA CLARA (LOMA)
	EL MOGOTE
	EL FIRME (SEC. GINA CLARA)
	GINA CLARA (INTERIOR)
	CUESTA BLANCA
	LOS CAFES
	LAS PIEDRAS (LLANO)
	JUANA DIAZ, SECCION
	EL TABLON
	NIGUA ABAJO
	NIGUA ABAJO (RURAL)
	LA MORA
	LA MORA (RURAL)
	JIMENEZ
	JIMENEZ (RURAL)
	LA LOMETA (LOMA)
	JUANA DIAZ (LLANO)
	JUANA DIAZ ARRIBA (LOMA)
	LA ZARZA SEC. JUANA DIAZ)
	LOS GUARAGUAOS
	EL FIRME (SEC. JUANA DIAZ)
	LOS CACHONES, SECCION
	EL RUCIO ABAJO (LLANO)
	LOS CACHONES ABAJO (LLANO)
	LOS CACHONES ABAJO (LLANO) (RURAL)
	LOS CACHONES ARRIBA (LOMA)
	LOS CALLEJONES
	EL SALADILLO
	EL RUCIO DE LOS CACHONES
	SABANA GRANDE (LLANO, SEC. LOS CACHONES)
	SABANA GRANDE (LLANO, LOS CACHONES, RURAL)
	LOS LANOS, SECCION
	CRUCE DE MAGUA
	CRUCE DE MAGUA (RURAL)
	CRUCE DE LOS LANOS
	CRUCE DE LOS LANOS (RURAL)
	LOS LANOS (LOMA)
	LOS LANOS (LOMA) (RURAL)
	QUEBRADA DE PABLO
	QUEBRADA DE PABLO (RURAL)
	LA CEIBITA
	LOS NARANJOS (SEC. LOS LANOS)
	LA JAGUITA (SEC. LOS LANOS)
	LOMA VIEJA
	EL RUCIO DE LOS LANOS
	RINCON HONDO, SECCION
	EL FIRME (SEC. RINCON HONDO)
	LAS PIEDRITAS
	LA JAGUA (SEC. RINCON HONDO)
	RINCON HONDO
	RINCON HONDO (RURAL)
	EL ALTO
	LAS CAOBAS ARRIBA
	LA MARGA (SEC. RINCON HONDO)
	LAS CAOBAS ABAJO
	LAS CAOBAS ABAJO (RURAL)
	LA GUAZARITA
	LAS BERENJENAS
	YAIBA ABAJO, SECCION
	LA SABANA (SEC. YAIBA ABAJO)
	LA SABANA (RURAL, YAIBA ABAJO)
	PUEBLO NUEVO (SEC. YAIBA ABAJO)
	PUEBLO NUEVO (RURAL, YAIBA ABAJO)
	RINCON DE YAIBA
	RINCON DE YAIBA (RURAL)
	CURAZAO (LOMA)
	YANABO ABAJO
	LOS PAMARITOS
	LA GARATA
	LA JOYA (SEC. JAIBA ABAJO)
	MAJAGUAL
	YANABO ARRIBA
	YAIBA ABAJO (LLANO)
	YAIBA ABAJO (LLANO) (RURAL)
	YAIBA ARRIBA (LOMA)
	HOSTOS, DIST. MUNICIPAL (ALREDEDORES)
	HOSTOS, CENTRO DEL PUEBLO
	EL PLAY (HOSTOS)
	LA JINA (HOSTOS)
	DAVID (HOSTOS)
	CUATRO
	LOS GUANDULES
	ACICATE, SECCION
	JUANA DIAZ ABAJO (LLANO)
	ACICATE
	ACICATE (RURAL)
	SABANA DE LA CEIBA
	SABANA DE LA CEIBA (RURAL)
	ACICATE DENTRO
	LA GINA O MATA GRANDE
	LA GINA O MATA GRANDE (RURAL)
	RIO YUNA
	CERREJON, SECCION
	ATORO (LLANO)
	ATORO (LOMA)
	CERREJON (LLANO)
	CARREJON (LOMA)
	LA ISLETA (LLANO)
	LA ISLETA (LOMA)
	CIEN TAREAS (LLANO)
	CIEN TAREAS (LOMA)
	SABANA GRANDE, SECCION (LLANO)
	EL CASERIO
	EL CASERIO (RURAL)
	RESBALON
	LA CULATA (SEC. SABANA GRANDE)
	LA CULATA (RURAL, SEC. SABANA GRANDE)
	MARIA HERNANDEZ
	MARIA HERNANDEZ (RURAL)
	BOCA DE YUCA
	SABANA GRANDE
	SABANA GRANDE (RURAL)
	LA YUCA
	PIMENTEL, MUNICIPIO
	LA JABILLA
	PIMENTEL, CENTRO DEL PUEBLO
	PIMENTEL, ZONAS ALEDAÑAS
	CEMENTERIO
	BUENA VISTA, SECCION
	LA JAGUA (SEC. BUENA VISTA)
	BUENA VISTA
	CATALINA
	GUANABANO
	CAOBETE, SECCION
	CAOBETE
	CAOBETE ARRIBA
	RINCON MARTIN
	LOS LIMONES (SEC. CAOBETE)
	RINCONAZO
	CAOBETE(SECCION MONTE NEGRO)
	CUABA ABAJO, SECCION
	MATUAN ABAJO
	EL PUENTE DE CAMU
	CUABA ABAJO
	CUABA ABAJO (RURAL)
	LA ESTANCIA
	LA ESTANCIA (RURAL)
	CASA DE ALTO (SEC. CUABA ABAJO)
	CASA DE ALTO (SEC. CUABA ABAJO, RURAL)
	LA EXCAVACION
	LA CHANCLETA (SEC. CUABA ABAJO)
	SANTA MARTHA
	CAMPECHE ARRIBA
	LA BARCA
	LA GINA (SEC. CUABA ABAJO)
	LA GINA (RURAL)
	CAMPECHE ABAJO
	SAN FELIPE ARRIBA (LOMA), SECCION
	LA GALANA
	ALTO DEL CAIMITO
	SAN FELIPE ARRIBA
	QUEBRADA DE LOS PATOS
	LA BERRAZA (LLANO)
	LOS CALLEJONES (LOMA)
	SAN FELIPE ABAJO (LLANO)
	VILLA RIVAS, MUNICIPIO
	ABREU (VILLA RIVAS)
	NUEVO, BARRIO O LA 50
	FRANCISCO RODRIGUEZ
	LA YAGUITA (VILLA RIVAS)
	SAN ANTONIO
	LOS RIELES
	EL MANGUITO (VILLA RIVAS)
	EL MATADERO
	VILLA RIVAS, CENTRO DEL PUEBLO
	CIUDAD NUEVA
	BUENOS AIRES A (VILLA RIVAS)
	BUENOS AIRES B (VILLA RIVAS)
	AGUA SANTA DEL YUNA, SECCION
	CRISTAL (LLANO)
	CRISTAL (LLANO) (RURAL)
	CRISTAL (LOMA)
	CRISTAL (LOMA) (RURAL)
	PARAGUAY (LLANO)
	PARAGUAY (LLANO) (RURAL)
	PARAGUAY (LOMA)
	PARAGUAY (LOMA) (RURAL)
	BOROJOL (LLANO)
	CALLEJON DE TILO
	EL ARADO
	LINDO, BO.
	LAUREL
	LA REFORMA
	EL MURO
	BARRAQUITO (LLANO)
	BARRAQUITO (LLANO) (RURAL)
	BARRAQUITO (LOMA)
	LA CUEVA (LLANO)
	LA CUEVA (LOMA)
	LA PISTA
	GUARAGUAO (LLANO)
	GUARAGUAO (LLANO) (RURAL)
	GUARAGUAO (LOMA)
	LOS PEYNADOS
	CAÑO AZUL (LLANO)
	CAÑO AZUL (LOMA)
	LA MINA DE LOS PEYNADOS
	LA MINA DE LOS PEYNADOS (LOMA)
	LOS CONTRERAS (LLANO)
	LOS CONTRERAS (LOMA)
	CEIBA DE LOS PAJAROS, SECCION
	JUNCO VERDE
	LA CEIBA ABAJO
	LOS COCOS (SEC. CEIBA DE LOS PAJAROS)
	REVENTAZON (LLANO)
	REVENTAZON (LOMA)
	LOS NARANJOS (LLANO, SEC. CEIBA DE LOS P.)
	LOS NARANJOS (LOMA, CEIBA DE LOS P.)
	BOCA DE CEVICOS (LLANO)
	BOCA DE CEVICOS (LOMA)
	LOMA COLORADA (LOMA)
	CEIBA DE LOS PAJAROS (LLANO)
	PAYABO
	CHIRINGO, SECCION
	LAS HORMIGAS
	EL MANGUITO (SEC. CHIRINGO)
	LOMA ABAJO (LOMA)
	EL HIGUERO (LOMA)
	CHIRINGO (LOMA)
	ZUMBA (LOMA)
	RINCON DE MAJAGUAL (LLANO)
	LOMA ARRIBA (LOMA)
	ALTO DE BULULO (LOMA)
	LAS TARANAS, SECCION
	EL ABANICO (LLANO)
	EL ABANICO (LLANO) (RURAL)
	DAVID (LAS TARANAS)
	EL BOMBILLO (LLANO)
	EL BOMBILLO (LLANO) (RURAL)
	CASTAÑOS (LLANO)
	LA PUNTA (LOMA)
	LAS TARANAS (LLANO)
	LAS TARANAS (LLANO) (RURAL)
	BAIGUATE (LLANO)
	CEIBA GORDA (LOMA)
	JOBO DULCE (LOMA)
	LAS CAOBAS (LOMA, SEC. LAS TARANAS)
	EL INDIO (LLANO)
	EL INDIO (LLANO) (RURAL)
	EL CIRUELILLO (LOMA)
	JOBOBAN (LLANO)
	EL CAMPAMENTO (LLANO)
	FIRME DE LAS TARANAS (LOMA)
	YAIBA, SECCION
	BOMBA DEL YAIBA
	BOMBA DEL YAIBA (RURAL)
	AREVANO
	AREVANO (RURAL)
	LOS ESPINOS (SEC. YAIBA)
	LA BRUSCA
	JUANA RODRIGUEZ ARRIBA
	JUANA RODRIGUEZ ABAJO
	JUANA RODRIGUEZ ABAJO (RURAL)
	CRUCE DE SAN RAFAEL
	CRUCE DE SAN RAFAEL (RURAL)
	BOMBILLO ABAJO
	BOMBILLO ABAJO (RURAL)
	EL CAÑO
	EL CAÑO (RURAL)
	LAS GUARANAS, DIST. MUNIC. (ALREDEDORES)
	LAS GUARANAS, CENTRO DEL PUEBLO
	PUEBLO NUEVO (LAS GUARANAS)
	PUEBLO NUEVO (RURAL)
	IGLESIAS
	LAS GUARANAS, SECCION
	LA ENEA (LAS GUARANAS)
	LA ENEA (RURAL, LAS GUARANAS)
	HONDURAS (LA GUARANAS)
	HONDURAS (RURAL, LAS GUARANAS)
	EL HATO (LAS GUARANAS)
	EL HATO (LAS GUARANAS, RURAL)
	LOS RIVERA
	LOS RIVERA (RURAL)
	LOS GENAO
	LOS GENAO (RURAL)
	AGUAS VIVAS
	AGUAS VIVAS (RURAL)
	LA BERMA DEL CANAL
	LA BERMA DEL CANAL (RURAL)
	SAN JUAN
	SAN JUAN (RURAL)
	RINCON CAMU
	RINCON CAMU (RURAL)
	LA PALMITA
	LA PALMITA (RURAL)
	PUERTO RICO (LAS GUARANAS)
	PUERTO RICO (RURAL)
	SAN FRANCISCO DE MACORIS, CENTRO URBANO
	PISA COSTURA
	LOS WEBER
	PALMARES, URB.
	BALBI, RES.
	COTUI (CENTRO DE LA CIUDAD)
	ACAPULCO
	CENTRO DE LA CIUDAD (COTUI)
	DEPOSITO
	EL DORADO
	EL TAMARINDO
	HERNANDEZ
	HOSTOS
	JUAN SANCHEZ RAMIREZ
	LA ALTAGRACIA
	LA ESPERANZA
	LA FORTALEZA
	LA GALLERA
	LA YUCA
	LIBERTAD
	LIMPIO DEL HATO
	LOS ALGODONES
	LOS CAJUILES (COTUI)
	LOS COCOS
	LOS ESPAÑOLES
	LOS MINEROS (ROSARIO DOMINICANA)
	LOS TOCONES (COTUI)
	PUEBLO NUEVO (COTUI)
	SANTA ROSA
	SANTA ROSA. BO.
	EL CEMENTERIO
	TAVIQUE
	EL MERCADO
	SECTOR HOSPITAL
	LA GINITA
	LA PALMA
	SAN MARTIN,BO.
	LOS PINOS (RESIDENCIAL).
	HERFA,URB.
	VISTA DEL VALLE
	LOS MAESTROS
	LA CRUZ.BO.
	SANTA FE.
	SABANA DE ARMANDO
	SABANA DE ARMANDO,(RURAL)
	CABALLERO ABAJO (URBANO)
	ARROYO LAJA
	ATALAYA ABAJO
	ATALAYA ARRIBA
	BARRAQUITO
	CABALLEROS ABAJO (RURAL)
	COMEDERO ARRIBA
	EL ALTO DE SAMO
	EL DIVISO
	EL GUAO
	EL HOYO (CABALLERO)
	EL LLANO
	EL OCHO
	EL YOJO
	HAITI LA CUEVA
	HIGO GORDO
	LA BUCARA
	LA CIDRA
	LA LOMA (CABALLERO ABAJO)
	LA MAJAGUA
	LA MATIA
	LA SABANA (CABALLERO ABAJO)
	LA ZARZA
	LAS TRES CEIBAS
	LOMA BOMBA
	LOMA DE CABALLERO ABAJO
	LOMA DE COMEDERO
	LOMA DE LOS CAMACHO
	LOMA DEL GALLO
	LOS BOTADOS
	LOS CAFÉ
	LOS CARBORIES
	LOS CASCAJALES
	LOS CATUANES
	LOS PINOS
	PALMARITO
	REYNOSO
	RINCONAZO
	RODEO
	SABANA POSTRERA
	YUYO ABAJO
	LA YAUTIA,(RURAL)
	CHACUEY MALDONADO (SECCION)
	ARROYO GRANDE
	EL COROZO (CHACUEY)
	EL JAMITO
	EL LIMON (CHACUEY)
	LA ATRAVEZADA (CHACUEY)
	LA CAOBA
	LA CUEVA (CHACUEY)
	LA CULATA
	LA HONDONADA
	LA JAGUA
	LA JAVILLA
	LA LLAMADA (CHACUEY)
	LA PLACETA (CHACUEY)
	LAS LAJAS (CHACUEY)
	LOMA DE LA GALLINA
	LOS JOBOS
	LOS POMOS
	LOS TRES PASOS
	LOS YAGRUMOS
	NARANJOS
	TOJIN
	LA NAVISA
	HATILLO (SECCION)
	ALTO DE LA CASA
	CAPACHO
	COLORADO
	EL BROQUE
	EL COCO
	EL PLATANO
	HATILLO (RURAL)
	LA BOMBA (HATILLO)
	LA LOMA (HATILLO)
	LA TRINCHERA
	LAS CRUCES
	LOS CACAOS
	LOS RANCHOS
	MONTE NEGRO
	PALO DE CUABA
	PUEBLO VIEJO
	QUITA SUEÑO
	RANCHO ABAJO
	SABANA VERDE (HATILLO)
	SAN JUAN
	YABACOA
	ZINC
	LAS LAGUNAS (SECCION)
	ARROYO VUELTA (LAS LAGUNAS)
	EL HIGO
	EL RAYO
	EL YAGAL
	FATIMA-LA BASCUA
	LA PIÑITA
	LA QUEBRADITA
	LAS TRES BOCAS (LAS LAGUNAS)
	LOS NARANJOS
	MAGUACA
	PIEDRA IMAN
	TOCOA
	LAS LAGUNAS
	LOS CERROS (SECCION)
	CRUCE MAGUACA
	DUEY GRANDE
	DUEY PEQUEÑO
	EL DUEY
	EL LIMON (LOS CERROS)
	JOBO CLARO
	LA CABIRMA
	LA LLAMADA (LOS CERROS)
	LA SABANA (LOS CERROS)
	LA TRAVESIA
	LA YAYA
	LOS CALLEJONES
	LOS CAPACES (LOS CERROS)
	LOS CERROS DE DUEY
	SABANA DE DUEY
	SABANA LARGA (LOS CERROS)
	SABANA LARGA ARRIBA
	SABANA VERDE (LOS CERROS)
	VILLA RAZA
	PLATANAL (SECCION)
	BABARIO
	BARICO
	BOCA DE JIBE
	CAMINO REAL
	CHACUEY ABAJO
	DON MIGUEL
	EL AGUACATE (PLATANAL)
	EL AGUACATICO
	EL PUENTE
	EL RANCHO
	EL TOPE
	GUARDARRAYA
	LA VUELTA
	LA CULEBRA
	LA LOMA (PLATANAL)
	MATIAS
	SABANA ABAJO (PLATANAL)
	SABANA ARRIBA (PLATANAL)
	SABANA GRANDE ABAJO (SECCION)
	BENITO
	CAÑO HONDO
	CASTILLO
	COLONIA JUAN SANCHEZ RAMIREZ
	EL COROCITO
	EL GUANABANO
	EL LIMPIO (SABANA GRANDE)
	EL SALADILLO
	JIBE
	LA BOMBA (SABANA GRANDE)
	LA CEIBA
	LA LECHOSA
	LA MARGA
	LA PALMITA
	LA ROSA-LA COLONIA
	LA TUSA
	LA ZUMBADORA (SABANA GRANDE)
	LAS PALMILLAS
	MONTE CLARO
	RINCON HATO
	SABANA AL MEDIO
	SABANA GRANDE DE SABALLO
	VALLE GRANDE (SABANA GRANDE)
	ZAMBRANA ABAJO (SECCION)
	ARROYO VUELTA (ZAMBRANA ABAJO)
	CUMBA
	EL ALGARROBAL
	EL COTORRO
	EL LIMPIO (ZAMBRANA ABAJO)
	GUARDIAMON
	GURABO
	JABO CLARO
	LA ATRAVEZADA (ZAMBRANA ABAJO)
	LA CUEVA (ZAMBRANA ABAJO)
	LA JAGUA MOCHA
	LA PLACETA (ZAMBRANA ABAJO)
	LAS DOS PALMAS
	LAS LAJAS (ZAMBRANA ABAJO)
	LAS TRES BOCAS (ZAMBRANA ABAJO)
	LOS COROCITOS
	MARISCAO-EL MANGO
	SABANA REY
	ZAMBRANA ARRIBA
	CEVICOS
	LOS TOCONES (CEVICOS)
	BARRIO A
	ABADESA (SECCION)
	ARENOSO
	BATEY DOÑA MARIA
	BATEY JABONICO
	BATEY LAS ARENAS
	BATEY PIEDRA
	CAÑO DE NARANJO
	CASTELLAR
	CEVICOS ARRIBA
	CIENAGOTE
	COOPERATIVA
	CRUCE DE JAGUA
	CUESTA BLANCA
	DOÑA MARIA
	EL CACAO
	HOYA FRESCA
	LLANADA
	LOS CERCADILLOS
	LOS HIGIS
	LOS HOYOS (ABADESA)
	LOS MANATIES
	LOS MAPOLOS
	PALMAR
	PASO HONDO
	PIEDRA
	SABANA DEL RIO
	SONADOR
	VALLE GRANDE (ABADESA)
	BATERO (SECCION)
	BATERO ARRIBA
	CONSUMIDERO -GRAYUMBRAY
	EL CIGUAR-RAÑE
	EL TARANAL-CAIMITO
	LA CEIBITA
	LA LOMA (BATERO)
	LAGUNA GRANDE
	LAS GUAYIGAS
	LOS CAJUILES (BATERO)
	LOS PERALEJOS (BATERO)
	LOS TAMARINDOS
	PRIMERA BOCA (BATERO)
	SABANA ABAJO (BATERO)
	SABANA ARRIBA (BATERO)
	SABANA DEL MARISCO
	YUNITA
	FANTINO (CENTRO DEL PUEBLO)
	FANTINO (ALREDEDORES)
	SAN MIGUEL (SECCION)
	ALTO DEL PINO
	BACUMI
	CALLEJON
	COJOBAL
	COMEDERO ABAJO
	EL COROZO (SAN MIGUEL)
	EL CRUCE (SAN MIGUEL)
	HATO MAYOR
	LA LAJA (SAN MIGUEL)
	LA PIEDRA (SAN MIGUEL)
	LOS CAYUCOS
	LOS PUENTECITOS
	PATRIA NUEVA
	SABANA LARGA (SAN MIGUEL)
	SABANA LOS CASTAÑOS
	SAN MIGUEL ABAJO
	SAN MIGUEL ARRIBA
	HATO MAYOR (RURAL)
	SIERRA PRIETA (SECCION)
	BATON-CALIENTE
	BERRINCHE-LOS COROZOS
	CAMU-PROYECTO CANAAN
	DON JUAN
	EL CAN
	EL CRUCE (SIERRA PRIETA)
	EL HOYO (SIERRA PRIETA)
	EL PINITO
	LA CENIZA
	LA CONCE
	LA GUACARA (SIERRA PRIETA)
	LA REFORMA
	LA ROMANA ABAJO
	LA ROMANA ARRIBA
	LA SABANA (SIERRA PRIETA)
	LOS BEJUCOS
	LOS CAPACES (SIERRA PRIETA)
	LOS CERROS (SIERRA PRIETA)
	LOS HOYOS (SIERRA PRIETA)
	PIÑA AL MEDIO
	PIÑA VIEJA
	LA CUEVA (CENTRO DEL PUEBLO)
	LA TETA
	NUEVA YORK
	UNION
	LA CUEVA (SECCION)
	EL POZO DE COLI
	EL POZO DE LA CEIBA
	HOYO DE LUIS
	LA CEIBA VIEJA
	LA GUACARA (LA CUEVA)
	LA MORA
	LA ZUMBADORA (LA CUEVA)
	LOS HAITISES
	LOS MAMEYES
	SABANA GRANDE (SECCION)
	EL CAÑO
	LA COLECITA
	LOS PERALEJOS (SABANA GRANDE)
	PRIMERA BOCA (SABANA GRANDE)
	SABANA CHIQUITA
	SABANA GRANDE
	SABANETA
	LA MATA (CENTRO DEL PUEBLO)
	EL CRUCE (LA MATA)
	EL PLAY
	INESPRE
	LA CIGUA-EL LIMPIO
	LA MATICA
	LOS HIGUEROS
	MONTE ADENTRO
	MONTE RIO
	LA MATA (ZONAS ALEDAÑAS)
	CANTA LA RANA
	AMOR Y PAZ,BO.
	INDRHI,BO.
	ANGELINA (SECCION)
	EL CRUCE DE ANGELINA
	EL LIMONCITO
	EL REMOLINO
	GUACHUPITA
	HOYO DE ORO
	LA PALOMA (BATEY SOTO)
	LOS CASTELLANOS (RIO VIEJO)
	PADRE FANTINO (MELAZA)
	PESCOSON
	RINCON MODERNO
	LA FORTUNA DE ANGELINA, BO. (COTUI)
	LA BIJA (SECCION)
	AGUIRRE (GUIRRE)
	BOCA DE CAMU
	CABEZA DE TORO
	EL CANAL
	EL CHARCO
	HATO VIEJO
	HIGUERITO-LA FACTORIA
	LA CUBA
	LA PIEDRA (LA BIJA)
	LA SOLEDAD
	MAINELY
	MATA DE CONUCO
	PUEBLO NUEVO (LA BIJA)
	LA SOLEDAD (RURAL)
	LA BIJA (RURAL)
	LOS HIGUERITOS
	LA CANA (SECCION)
	BOMA
	LA PIEDRA (LA CANA)
	LAS AUYAMAS
	LAS GUAMITAS
	LOMA DEL BURRO
	MONTE ABAJO (LA CANA)
	RINCON GRANDE
	LOS COROZOS (SECCION)
	AGUA SARCA
	EL POZO
	LA LAJA (LOS COROZOS)
	LA PIÑITA
	LA RECTA
	MONTE ABAJO (LOS COROZOS)
	SANTA POLA
	TRIPULACION
	VEREDA DE YUNA
	LOS COROZOS (LOMA)
	HERNANDO ALONZO (SECCION)
	EL AGUACATE (HERNANDO ALONZO)
	EL CASERIO
	EL CERCADO
	EL HATO
	EL HOYO (HERNANDO ALONZO)
	EL HUNDIDERO
	LA POCILGA
	LA SABANA (HERNANDO ALONZO)
	LOMA EL PEÑON
	LOS BRAZOS
	LOS CERROS (HERNANDO ALONZO)
	LOS CONUCONES
	LOS PALMARITOS
	PISAÑA
	PUNTA LARGA
	QUEBRADA HONDA
	RODEO
	SABANA DE MELADITO



EOD;

//foreach(Environment_vars::$maps['texts_to_id']['property_neighborhoods']['Santo Domingo'] as $name => $id)
//{
//    echo utf8_decode($name) , '<br/>';
//    
//}
//    
//    
//    die;
        
        
        $regex = '/(\w+[ \wáéíúóA-ZÁÉÍÓÚñÑ(),\.\/\-\(\)]*)/';

        $replace_regex = "\$this->execute(\"INSERT INTO neighborhoods (name,province_id) VALUES ('$1', 33)\"); <br/> \$this->execute(\"INSERT INTO neighborhoods_provinces (province_id,neighborhood_id) VALUES (6, \$i)\");";
        
        
        

        $count = 0;


        $strings = explode("\n", $replace_string);
        
        $i = 345;
        foreach ($strings as $string) {
            $i++;

                $replace = str_replace("\$i", $i, $replace_regex);
              
             echo utf8_decode(preg_replace($regex, $replace, $string)) ;
             echo '<br/>';
             
        }
        
        
        
    }

}

?>
