<?php

/*
 */

class Environment_vars {

    public static $google_api = array("developer_id" => "AI39si58bPU3fVlTrF8i4eyximJ9qMl8NMgJpUCxF1DMAIZAR-TTYUTftwkTSfx0m9D7PNXdnYDHwCxOmV-M6Kfy6lrQeePGfg", "aplication_id" => "Propiedom");
    public static $youtube= array("username" => "arielalvarez88@gmail.com", "password" =>"D3s1gnp@tt3rns");


    public static $environment = "production";
    public static $maps = array(
        "file_type_to_id" => array("photo" => 1, "video" => 2),                
        "user_type_to_validation_rules" => array("client" => "signupClient", "company" => "signupCompany", "edit_client" => "edit_clent"),
        "property_types" => array(
            "house" => 1,
            "apartment" => 2,
            "lot" => 3,
            "penthouse" => 4,
            "mall" => 5,
            "building" => 6,
            "warehouse" => 7,
            "office" => 8,
            "land" => 9,
            "construction_project" => 10
        ),
        "property_conditions" => array("sell" => "1", "rent" => 2, "sell/rent" => 3),
        "filter-fields-to-db-fields" => array("sector" => "sector", "condition" => "condition"),
        "property_types" => array(
            "house" => 1,
            "apartment" => 2,
            "lot" => 3,
            "penthouse" => 4,
            "mall" => 5,
            "building" => 6,
            "warehouse" => 7,
            "office" => 8,
            "land" => 9,
            "construction_project" => 10
        ),
        "texts_to_id" => array(
  "property_close_places" => array(
            "close-malls" => 1,
            "close-supermarkets" => 2,
            "close-grocery-stores" => 3,
            "close-schools" => 4,
            "close-restaurants" => 5,
            "close-bakeries" => 6,
            "close-gyms" => 7,
            "close-public-transport" => 8,
            "close-hardware-stores" => 9,
            "close-drug-stores" => 10
        ),
 "property_feature" => array(
            "elevator" => 1,
            "game-area" => 2,
            "wash-area" => 3,
            "balcony" => 4,
            "recreative-areas-bathrooms" => 5,
            "electric-water-heater" => 6,
            "gas-water-heater" => 7,
            "watchman-stand" => 8,
            "cistern" => 9,
            "white-clothes-closet" => 10,
            "equiped-kitchen" => 11,
            "dinning-room" => 12,
            "antisismic-construction" => 13,
            "plaster-cornices" => 14,
            "machine-room" => 15,
            "utility-room-bathroom" => 16,
            "counter-top" => 17,
            "pantry" => 18,
            "trash-chute" => 19,
            "principal-room-bathroom" => 20,
            "family-room" => 21,
            "common-gas" => 22,
            "imported-fittings" => 23,
            "intercom" => 24,
            "jacuzzi" => 25,
            "garden" => 26,
            "kiosk" => 27,
            "lobby" => 28,
            "double-garage" => 29,
            "half-bathroom" => 30,
            "receiver" => 31,
            "extra-parkings" => 32,
            "patio-with-garden" => 33,
            "pool" => 34,
            "marmol-floors" => 35,
            "electric-plant" => 36,
            "mahogany-terminations" => 37,
            "terrace" => 38,
            "pre-installed-services" => 39,
            "granite-countertops" => 40,
            "electric-gate" => 41,
            "walk-in-closet" => 42,
            'fernatured' => 43,
		'alarm' => 44,
		'tinaco' => 45
        ),
'Admin_user_type' => 100,
            "requesters_user_to_active_user" => array("Particular" => 1,  "Empresa" => 2 , "Agente Independiente"=>4),
            "user_types" => array("Particular" => 1, "Empresa" => 2, "Agente de Empresa" => 3, "Agente Independiente" => 4),
            "plans"=>array("Basico"=>1, "Plus"=>2,"Agente"=>3,"Inmobiliaria"=>4),
            "user_types_requesters" => array("Particular" => 5, "Empresa" => 6, "Agente Independiente" => 8),
            "user_types_if_not_company" => array("Particular" => 1, "Empresa" => 2, "Agente Independiente" => 4),
"property_neighborhoods" => array(
                   "Santiago" => array(
    'Altos de Virella' => 1,
    'Autopista Duarte' => 2,
    'Av. 27 de Febrero' => 3,
    'Av. Juan Pablo Duarte' => 4,
    'Baracoa' => 5,
    'Barrio Lindo' =>6,
    'Barrio Los Santos'=>7,
    'Bella Vista' => 8,
    'Brisas del Este'=>9,
    'Buenos Aires'=>10,
    'Casilda'=>11,
    'Centro Ciudad'=>12,
    'Cerro Alto'=>13,
    'Cerro Hermoso'=>14,
    'Cerros de Gurabo I'=>15,
    'Cerros de Gurabo II'=>16,
    'Cerros de Gurabo III'=>17,
    'Cerros Doña Julia'=>18,
    'Cienfuegos'=>19,
    'Ciudad Deportiva'=>20,
    'Corona Plaza'=>21,
    'Cuesta Colorada'=>22,
    'Domingo Bermúdez'=>23,
    'El Congo'=>24,
    'El Despertar'=>25,
    'El Dorado'=>26,
    'El Dorado II'=>27,
    'El Doral'=>28,
    'El Edén'=>29,
    'El Ejido'=>30,
    'El Embrujo I'=>31,
    'El Embrujo II'=>32,
    'El Ensueño'=>33,
    'El Ingenio'=>34,
    'El Invi'=>35,
    'El Paraíso'=>36,
    'El Portal'=>37,
    'El Retiro'=>38,
    'Ensache Ortega'=>40,
    'Ensanche Bermúdez'=>41,
    'Ensanche Caonabo'=>42,
    'Ensanche Dolores'=>43,
    'Ensanche Espaillat'=>44,
    'Ensanche Julia I'=>45,
    'Ensanche Julia II'=>46,
    'Ensanche Román'=>47,
    'Ensanche Simón Bolívar'=>48,
    'Flor de Gurabo'=>49,
    'Gregorio Luperón'=>50,
    'Gurabito'=>51,
    'Gurabo Abajo'=>52,
    'Gurabo al Medio'=>53,
    'Gurabo Arriba'=>54,
    'Hato Mayor'=>55,
    'Hermanas Mirabal'=>56,
    'Hoya del Caimito'=>57,
    'Jardines del Este'=>58,
    'Jardines del Norte'=>59,
    'Jardines del Oeste'=>60,
    'Jardines Dorado'=>61,
    'La Arboleda'=>62,
    'La Barranquita'=>63,
    'La Catalina'=>64,
    'La Ermita'=>65,
    'La Esmeralda'=>66,
    'La Española'=>67,
    'La Fardiquera'=>68,
    'La Gallera'=>69,
    'La Herradura'=>70,
    'La Joya'=>71,
    'La Junta'=>72,
    'La Lotería'=>73,
    'La Mina'=>74,
    'La Moraleja'=>75,
    'La Otra Banda'=>76,
    'La Rinconada'=>77,
    'La Terraza'=>78,
    'La Trinitaria'=>79,
    'La Zurza I'=>80,
    'La Zurza II'=>81,
    'La Zurza III'=>82,
    'Las Américas'=>83,
    'Las Antillas'=>84,
    'Las Carmelitas'=>85,
    'Las Charcas'=>86,
    'Las Colinas'=>87,
    'Las Damas'=>88,
    'Las Dianas'=>89,
        'Las Hortensias'=> 90,
'Las Palmas'=>91,
'Las Praderas'=>92,
'Las Praderas'=>93,
'Limonal Abajo'=>94,
'Llanos de Gurabo'=>95,
'Llanos de Gurabo II'=>96,
'Los Alamos'=>97,
'Los Cajuiles'=>98,
'Los Castillos'=>99,
'Los Cerritos'=>100,
'Los Ciruelitos'=>101,
'Los Colegios'=>102,
'Los Girasoles'=>103,
'Los Guandules'=>104,
'Los Hidalgos'=>105,
'Los Jardines Metropolitanos'=>106,
'Los Jazmines'=>107,
'Los Laureles'=>108,
'Los Llanos de Gurabo'=>109,
'Los Mera'=>110,
'Los Moran'=>111,
'Los Reyes I'=>112,
'Los Reyes II'=>113,
'Los Rieles'=>114,
'Los Robles'=>115,
'Los Salados'=>116,
'Los Samanes'=>117,
'Mainardi Reyna'=>118,
'Marilopez'=>119,
'Mejoramiento Social'=>120,
'Monte Verde'=>121,
'Monterico'=>122,
'Nibaje'=>123,
'Nuevo Amanecer'=>124,
'Padre Las Casas'=>125,
'Paseo del Prado'=>126,
'Paseo Verde'=>127,
'Pedro Fco. Bono'=>128,
'Pekín'=>129,
'Pontezuela Abajo'=>130,
'Pontezuela al Medio'=>131,
'Prados del Yaque'=>132,
'Pueblo Nuevo'=>133,
        'Quintas de Pontezuela'=>134,
'Reparto Consuelo'=>135,
'Reparto del Este'=>136,
'Reparto Hache'=>137,
'Reparto Ilusión'=>138,
'Reparto Imperial'=>139,
'Reparto Kokette'=>140,
'Reparto Oquet'=>141,
'Reparto Peralta'=>142,
'Reparto Perelló' => 143,
'Reparto Tavares'=>144,
'Reparto Universitario'=>145,
'Res. Amapola'=>146,
'Rincón Largo'=>147,
'Sabaneta de las Palomas'=>148,
'San José'=>149,
'Savica'=>150,
'Tierra Alta'=>151,
'Urb. Alejo'=>152,
'Urb. Fernández'=>153,
'Urb. Fernando Valerio'=>154,
'Urb. Gutiérrez'=>155,
'Urb. Hacienda Palmeral'=>156,
'Urb. La Rosa'=>157,
'Urb. Marol'=>158,
'Urb. Miraflores'=>159,
'Urb. Monumental'=>160,
'Urb. Las Cayenas'=>161,
'Urb. Henríquez'=>162,
'V Centenario'=>163,
'Villa Esperanza'=>164,
'Villa María'=>165,
'Villa Noa'=>166,
'Villa Olga'=>167,
'Villa Olímpica'=>168,
'Villa Progreso II'=>169,
'Villa Sor Ángel'=>170,
'Villa Verde'=>171,
'Vistas del Cerro'=>172,
'Yoryi Morel'=>173,
'Zamarrilla'=>174



    ),
    "Santo Domingo" => array(

    
    "Alameda" => 1,
    "Altos de Arroyo Hondo II" => 2,
    "Altos de Arroyo Hondo III "=> 3,
    "Antillas"=>4,
    "Arroyo Hondo "=> 5,
    "Arroyo Hondo Viejo "=> 6,
    "Atala "=> 7,
    "Bella Vista "=> 8,
    "Buenos Aires "=> 10,
    "Centro de los Heroes" => 12,
    "Cerros Arroyo Hondo III" => 14,
    "Cerros de Arroyo Hondo" =>15,    
    "Ciudad Moderna"=>16,
    "Ciudad Nueva" => 17,
    "Ciudad Universitaria "=> 18,
    "Costa Brava"=>19,
    "Cuesta Hermosa I"=>20,
    "Cuesta Hermosa II"=>21,
    "Cuesta Hermosa III"=>22,
    "Dominicanos Ausentes"=>23,
    "Don Bosco"=>24,
    "El Cacique"=>25,
    "El Millon"=>26,
    "El Millon II"=>27,
    "El Portal"=>28,
    "El Vergel"=>29,
    "Encarnacion"=>30,
    "Enriquillo"=>31,    
    "Ens. La F"=> 32,
    "Ens. La Paz"=> 33,
    "Ens. Luperón"=> 34,
    "Ens. Naco "=> 35,
    "Ens. quisqueya" => 36,
    "Ensanche Carmelita"=>37,
    "Ensanche Julieta"=>38,
    "Ensanche Miraflores"=>39,
    "Ensanche Paraiso"=>40,
    "Ensanche Quisqueya" =>41,
    "Evaristo Morales"=>42,    
    "Gacela"=>43,
    "Gazcue"=>44,
    "Helios del Oeste"=>45,
    "Herrera"=> 46,
    "Honduras"=>47,
    "Honduras del Norte"=>47,
    "Honduras del Oeste"=>48,
    "Jardines del Caribe"=>49,
    "Jardines del Embajador"=>50,
   "JJulieta Morales"=> 51,
    "La Agustina"=>52,
    "La Castellana"=>53,
    "La Esperilla"=>54,    
    "La Feria"=>55,
    "La Julia"=>56,    
    "Laderas de Arroyo Hondo"=>57,
    "Las Caobas"=>58,
    "Las Colinas de los Rios"=>59,
    "Las Praderas"=>60,
    "Lomas de Arroyo Hondo"=>61,
    "Los Cacicazgos"=>62,    
    "Los Hidalgos"=>63,
    "Los Jardines del Norte"=> 64,
    "Los Maestros"=>65,
    "Los Prados"=>66,
    "Los Prados"=> 67,
    "Los Restauradores"=>68,    
    "Los Rios"=>69,
    "Loteria"=>70,
    "Manganagua"=>71,
    "Mar Azul"=>72,
    "María Auxiliadora" => 72,
    "Mata Hambre"=> 73,
    "Matahambre"=>74,
    "Mirador Norte"=>75,    
    "Mirador Sur"=>76,   
    "Miraflores" => 77,
    "Miramar"=>78,
    "Naco"=>79,
    "Nuevo Arroyo Hondo"=>80,
    "Paraiso"=>81,
    "Piantini"=>82,
    "Renacimiento"=>83,
    "Res. Rosmil"=>84,
    "Residencial Jose Contreras"=>85,
    "San Carlos"=> 86,
    "San Geronimo"=>87,
    "Serralles"=>88,
    "Tropical"=>87,
    "Urb. Atlantida"=>88,
    "Urb. Fernandez"=>89,
    "Urbanizacion Marien"=>90,
    "Urbanizacion Real"=>91,
    "Villa Claudia"=>91,
    "Villa Consuelo"=> 92,
    "Villa Juana"=> 93,
    "Villa Marina"=>94,
    "Yolanda Morales"=>95,
    "Zona Colonial"=>96,
    "Zona Industrial de Herrera"=>97,
    "Zona No Disponible"=>98,
    "Zona Universitaria"=>99
    )
                ),
            "property_conditions" => array("Venta" => 1, "Alquiler" => 2, "Venta/Alquiler" => 3),
            "property_conditions_for_filter" => array("Venta" => 1, "Alquiler" => 2),
            "property_types" => array("Casa" => 1, "Apartamento" => 2, "Penthouse" => 3, "Local Comercial" => 4, "Edificio" => 5, "Nave Industrial" => 6, "Oficina" => 7, "Solar" => 8, "Finca" => 9, "Proyecto en Construcción" => 10),
            "provinces" => array("Azua" => 1,
                "Bahoruco" => 2,
                "Barahona" => 3,
                "Dajabón" => 4,
                "Distrito Nacional" => 5,
                "Duarte" => 6,
                "Elías Piña" => 7,
                "El Seibo" => 8,
                "Espaillat" => 9,
                "Hato Mayor" => 10,
                "Hermanas Mirabal" => 11,
                "Independencia" => 12,
                "La Altagracia" => 13,
                "La Vega" => 14,
                "María Trinidad Sánchez" => 15,
                "Monseñor Nouel" => 16,
                "Montecristi" => 17,
                "Monte Plata" => 18,
                "Pedernales" => 19,
                "Peravia" => 20,
                "Puerto Plata" => 21,
                "Samaná" => 22,
                "Sánchez Ramírez" => 23,
                "San Cristóbal" => 24,
                "San José de Ocoa" => 25,
                "San Juan" => 26,
                "San Pedro de Macorís" => 27,
                "Santiago" => 28,
                "Santiago Rodríguez" => 29,
                "Santo Domingo" => 30,
                "Valverde" => 31),
            'search_order_by_options' => array( "Precio Mayor a Menor" => 1,  "Precio Menor a Mayor" => 2,  "Provincia" => 3)
        ),
        "ids_to_text" => array(
 "property_feature" => array(
                1 => "elevator",
                2 => "game-area",
                3 => "wash-area",
                4 => "balcony",
                5 => "recreative-areas-bathrooms",
                6 => "electric-water-heater",
                7 => "gas-water-heater",
                8 => "watchman-stand",
                9 => "cistern",
                10 => "white-clothes-closet",
                11 => "equiped-kitchen",
                12 => "dinning-room",
                13 => "antisismic-construction",
                14 => "plaster-cornices",
                15 => "machine-room",
                16 => "utility-room-bathroom",
                17 => "counter-top",
                18 => "pantry",
                19 => "trash-chute",
                20 => "principal-room-bathroom",
                21 => "family-room",
                22 => "common-gas",
                23 => "imported-fittings",
                24 => "intercom",
                25 => "jacuzzi",
                26 => "garden",
                27 => "kiosk",
                28 => "lobby",
                29 => "double-garage",
                30 => "half-bathroom",
                31 => "receiver",
                32 => "extra-parkings",
                33 => "patio-with-garden",
                34 => "pool",
                35 => "marmol-floors",
                36 => "electric-plant",
                37 => "mahogany-terminations",
                38 => "terrace",
                39 => "pre-installed-services",
                40 => "granite-countertops",
                41 => "electric-gate",
                42 => "walk-in-closet",
                43 => 'fernatured',
		44 => 'alarm',
		45 => 'tinaco'),
             "property_close_places" => array(
            1 => "close-malls",
            2 => "close-supermarkets",
            3 => "close-grocery-stores",
            4 => "close-schools",
            5 => "close-restaurants",
            6 => "close-bakeries",
            7 => "close-gyms",
            8 => "close-public-transport",
            9 => "close-hardware-stores",
            10 => "close-drug-stores"
        ),
            "user_types_requesters" => array(5 => "Particular", 6=> "Empresa", 8 => "Agente Independiente"),
            'search_order_by_options' => array( "price DESC" => 1,  "price ASC" => 2,  "province" => 3, "id" => 4),
            "property_types" => array(1 => "Casa", 2 => "Apartamento", 3 => "Penthhouse", 4 => "Centro Comercial", 5 => "Edificio", 6 => "Nave Industrial", 7 => "Oficina", 8 => "Solar", 9 => "Finca", 10 => "Proyecto en Construcción"),
            "property_types_validation" => array(
                1 => "house",
                2 => "apartment",
                3 => "penthouse",
                4 => "mall",
                5 => "building",
                6 => "warehouse",
                7 => "office",
                8 => "land",
                9 => "lot",
                10 => "construction_project"
            ),
            "sell_rent_validation" => array(
                1 => "sell",
                2 => "rent",
                3 => "sell_rent",
            ),
            "property_neighborhoods" => array(1 => "Cerro Alto", 2 => "Villa Olga"),
            "provinces" => array( 
                1 => "Azua",
                2 => "Bahoruco" ,
                3 => "Barahona",
                4 => "Dajabón",
                5 => "Distrito Nacional",
                6 =>"Duarte" ,
                 7 =>"Elías Piña",
                 8 =>"El Seibo",
                9 => "Espaillat",
                10 => "Hato Mayor",
                11 => "Hermanas Mirabal",
                12 => "Independencia",
                13 => "La Altagracia",
                14 => "La Vega",
                15 => "María Trinidad Sánchez",
                16 => "Monseñor Nouel",
                17 => "Montecristi",
                18 => "Monte Plata",
                19 => "Pedernales",
                20 => "Peravia",
                21 => "Puerto Plata",
                22 => "Samaná",
                23 => "Sánchez Ramírez",
                24 => "San Cristóbal",
                25 => "San José de Ocoa",
                26 => "San Juan",
                27 => "San Pedro de Macorís",
                28 => "Santiago",
                29 => "Santiago Rodríguez",
                30 => "Santo Domingo",
                31 => "Valverde")
        ),
        "html_to_id" => array(
            "user_types" => array("particular" => 1, "empresa" => 2, "agente_de_empresa" => 3, "agente_independiente" => 4),
            "user_types_requesters" => array("particular" => 5, "empresa" => 6, "agente_independiente" => 8),
            "property_types" => array(
                "house" => 1,
                "apartment" => 2,
                "lot" => 3,
                "penthouse" => 4,
                "mall" => 5,
                "building" => 6,
                "warehouse" => 7,
                "office" => 8,
                "land" => 9
            )
        ),
        "id_to_html" => array(
            "property_types" => array(1 => "Casa", 2 => "Apartamento", 3 => "Solar", 4 => "Penthhouse", 5 => "Centro Comercial", 6 => "Edificio", 7 => "Nave Industrial", 8 => "Oficina", 9 => "Finca", 10 => "Proyecto")
        ),
        "property_close_places" => array(
            "close-malls" => 1,
            "close-supermarkets" => 2,
            "close-grocery-stores" => 3,
            "close-schools" => 4,
            "close-restaurants" => 5,
            "close-bakeries" => 6,
            "close-gyms" => 7,
            "close-public-transport" => 8,
            "close-hardware-stores" => 9,
            "close-drug-stores" => 10
        ),
        "property_features" => array(
            "elevator" => 1,
            "game-area" => 2,
            "wash-area" => 3,
            "balcony" => 4,
            "recreative-areas-bathrooms" => 5,
            "electric-water-heater" => 6,
            "gas-water-heater" => 7,
            "watchman-stand" => 8,
            "cistern" => 9,
            "white-clothes-closet" => 10,
            "equiped-kitchen" => 11,
            "dinning-room" => 12,
            "antisismic-construction" => 13,
            "plaster-cornices" => 14,
            "machine-room" => 15,
            "utility-room-bathroom" => 16,
            "counter-top" => 17,
            "pantry" => 18,
            "trash-chute" => 19,
            "principal-room-bathroom" => 20,
            "family-room" => 21,
            "common-gas" => 22,
            "imported-fittings" => 23,
            "intercom" => 24,
            "jacuzzi" => 25,
            "garden" => 26,
            "kiosk" => 27,
            "lobby" => 28,
            "double-garage" => 29,
            "half-bathroom" => 30,
            "receiver" => 31,
            "extra-parkings" => 32,
            "patio-with-garden" => 33,
            "pool" => 34,
            "marmol-floors" => 35,
            "electric-plant" => 36,
            "mahogany-terminations" => 37,
            "terrace" => 38,
            "pre-installed-services" => 39,
            "granite-countertops" => 40,
            "electric-gate" => 41,
            "walk-in-closet" => 42
        )
    );


public static $paths = array(
    'https_base_site' => 'http://www.propiedom.com',
    'default_company_photo' => '/images/common/defaultCompanyPhoto.png',
    'default_agent_photo' => '/images/common/defaultAgentPhoto.png',
    'user_photos_thumbs_dir_path' => '/images/userPhotosThumbs/',
'properties_photos_thumbs_dir_path' => 
'/images/propertiesPhotosThumbs/',
'default_particular_photo' => 
'/images/common/defaultParticularPhoto.png'
    );    
  
    public static $environment_vars = array(

        'user_photos_dir_path' => '/images/userPhotos/',
        'user_photos_thumbs_dir_path' => '/images/userPhotosThumbs/',
        'properties_photos_dir_path' => '/images/propertiesPhotos/',
        'properties_photos_thumbs_dir_path' => '/images/propertiesPhotosThumbs/'
    );
    public static $available_languages = array(
	"spanish",
	"english"
	);
}

?>
