<?php

/*
 */

class Environment_vars {

    public static $maps = array(
        "file_type_to_id" => array("photo" => 1, "video" => 2),
        "user_type_to_validation_rules" => array("client" => "signupClient", "company" => "signupCompany", "edit_client" => "edit_clent"),
        "property_feature_to_name" => array(
            1 => "elevator",
            2 => "game_area",
            3 => "wash_area",
            4 => "balcony",
            5 => "recreative_areas_bathrooms",
            6 => "electric_water_heater",
            7 => "gas_water_heater",
            8 => "watchman_stand",
            9 => "cistern",
            10 => "white_clothes_closet",
            11 => "equiped_kitchen",
            12 => "dinning_room",
            13 => "antisismic_construction",
            14 => "plaster_cornices",
            15 => "machine_room",
            16 => "utility_room_bathroom",
            17 => "counter_top",
            18 => "pantry",
            19 => "trash_chute",
            20 => "principal_room_bathroom",
            21 => "family_room",
            22 => "common_gas",
            23 => "imported_fittings",
            24 => "intercom",
            25 => "jacuzzi",
            26 => "garden",
            27 => "kiosk",
            28 => "lobby",
            29 => "double_garage",
            30 => "half_bathroom",
            31 => "receiver",
            32 => "extra_parkings",
            33 => "patio_with_garden",
            34 => "pool",
            35 => "marmol_floors",
            36 => "electric_plant",
            37 => "mahogany_terminations",
            38 => "terrace",
            39 => "pre_installed_services",
            40 => "granite_countertops",
            41 => "electric_gate",
            42 => "walk_in_closet"),
        "property_close_places_to_name" => array(
            1 => "close_malls",
            2 => "close_supermarkets",
            3 => "close_grocery_stores",
            4 => "close_schools",
            5 => "close_restaurants",
            6 => "close_bakeries",
            7 => "close_gyms",
            8 => "close_public_transport",
            9 => "close_hardware_stores",
            10 => "close_drug_stores"
        ),
        "property_types" => array(
            "house" => 1,
            "apartment" => 2,
            "lot" => 3,
            "penthouse" => 4,
            "mall" => 5,
            "building" => 6,
            "warehouse" => 7,
            "office" => 8,
            "land" => 9,
            "construction_project" => 10
        ),
        "property_conditions" => array("sell" => "1", "rent" => 2, "sell/rent" => 3),
        "filter-fields-to-db-fields" => array("sector" => "sector", "condition" => "condition"),
        "property_types" => array(
            "house" => 1,
            "apartment" => 2,
            "lot" => 3,
            "penthouse" => 4,
            "mall" => 5,
            "building" => 6,
            "warehouse" => 7,
            "office" => 8,
            "land" => 9,
            "construction_project" => 10
        ),
        "texts_to_id" => array(
            "user_types" => array("Particular" => 1, "Empresa" => 2, "Agente de Empresa" => 3, "Agente Independiente" => 4),
            "user_types_requesters" => array("Particular" => 5, "Empresa" => 6, "Agente Independiente" => 8),
            "user_types_if_not_company" => array("Particular" => 1, "Empresa" => 2, "Agente Independiente" => 4),
            "property_neighborhoods" => array("Cerro Alto" => "1", "Villa Olga" => 2),
            "property_conditions" => array("Venta" => 1, "Alquiler" => 2, "Venta/Alquiler" => 3),
            "property_conditions_for_filter" => array("Venta" => 1, "Alquiler" => 2),
            "property_types" => array("Casa" => 1, "Apartamento" => 2, "Penthouse" => 3, "Local Comercial" => 4, "Edificio" => 5, "Nave Industrial" => 6, "Oficina" => 7, "Solar" => 8, "Finca" => 9, "Proyecto en Construcción" => 10),
            "provinces" => array("Azua" => 1,
                "Bahoruco" => 2,
                "Barahona" => 3,
                "Dajabón" => 4,
                "Distrito Nacional" => 5,
                "Duarte" => 6,
                "Elías Piña" => 7,
                "El Seibo" => 8,
                "Espaillat" => 9,
                "Hato Mayor" => 10,
                "Hermanas Mirabal" => 11,
                "Independencia" => 12,
                "La Altagracia" => 13,
                "La Vega" => 14,
                "María Trinidad Sánchez" => 15,
                "Monseñor Nouel" => 16,
                "Montecristi" => 17,
                "Monte Plata" => 18,
                "Pedernales" => 19,
                "Peravia" => 20,
                "Puerto Plata" => 21,
                "Samaná" => 22,
                "Sánchez Ramírez" => 23,
                "San Cristóbal" => 24,
                "San José de Ocoa" => 25,
                "San Juan" => 26,
                "San Pedro de Macorís" => 27,
                "Santiago" => 28,
                "Santiago Rodríguez" => 29,
                "Santo Domingo" => 30,
                "Valverde" => 31),
            'search_order_by_options' => array( "Precio Mayor a Menor" => 1,  "Precio Menor a Mayor" => 2,  "Provincia" => 3)
        ),
        "ids_to_text" => array(
            'search_order_by_options' => array( "price DESC" => 1,  "price ASC" => 2,  "province" => 3, "id" => 4),
            "property_types" => array(1 => "Casa", 2 => "Apartamento", 3 => "Penthhouse", 4 => "Centro Comercial", 5 => "Edificio", 6 => "Nave Industrial", 7 => "Oficina", 8 => "Solar", 9 => "Finca", 10 => "Proyecto en Construcción"),
            "property_types_validation" => array(
                1 => "house",
                2 => "apartment",
                3 => "penthouse",
                4 => "mall",
                5 => "building",
                6 => "warehouse",
                7 => "office",
                8 => "land",
                9 => "lot",
                10 => "construction_project"
            ),
            "sell_rent_validation" => array(
                1 => "sell",
                2 => "rent",
                3 => "sell_rent",
            ),
            "property_neighborhoods" => array(1 => "Cerro Alto", 2 => "Villa Olga"),
            "provinces" => array( 
                1 => "Azua",
                2 => "Bahoruco" ,
                3 => "Barahona",
                4 => "Dajabón",
                5 => "Distrito Nacional",
                6 =>"Duarte" ,
                 7 =>"Elías Piña",
                 8 =>"El Seibo",
                9 => "Espaillat",
                10 => "Hato Mayor",
                11 => "Hermanas Mirabal",
                12 => "Independencia",
                13 => "La Altagracia",
                14 => "La Vega",
                15 => "María Trinidad Sánchez",
                16 => "Monseñor Nouel",
                17 => "Montecristi",
                18 => "Monte Plata",
                19 => "Pedernales",
                20 => "Peravia",
                21 => "Puerto Plata",
                22 => "Samaná",
                23 => "Sánchez Ramírez",
                24 => "San Cristóbal",
                25 => "San José de Ocoa",
                26 => "San Juan",
                27 => "San Pedro de Macorís",
                28 => "Santiago",
                29 => "Santiago Rodríguez",
                30 => "Santo Domingo",
                31 => "Valverde")
        ),
        "html_to_id" => array(
            "user_types" => array("particular" => 1, "empresa" => 2, "agente_de_empresa" => 3, "agente_independiente" => 4),
            "user_types_requesters" => array("particular" => 5, "empresa" => 6, "agente_independiente" => 8),
            "property_types" => array(
                "house" => 1,
                "apartment" => 2,
                "lot" => 3,
                "penthouse" => 4,
                "mall" => 5,
                "building" => 6,
                "warehouse" => 7,
                "office" => 8,
                "land" => 9
            )
        ),
        "id_to_html" => array(
            "property_types" => array(1 => "Casa", 2 => "Apartamento", 3 => "Solar", 4 => "Penthhouse", 5 => "Centro Comercial", 6 => "Edificio", 7 => "Nave Industrial", 8 => "Oficina", 9 => "Finca", 10 => "Proyecto")
        ),
        "property_close_places" => array(
            "close-malls" => 1,
            "close-supermarkets" => 2,
            "close-grocery-stores" => 3,
            "close-schools" => 4,
            "close-restaurants" => 5,
            "close-bakeries" => 6,
            "close-gyms" => 7,
            "close-public-transport" => 8,
            "close-hardware-stores" => 9,
            "close-drug-stores" => 10
        ),
        "property_features" => array(
            "elevator" => 1,
            "game-area" => 2,
            "wash-area" => 3,
            "balcony" => 4,
            "recreative-areas-bathrooms" => 5,
            "electric-water-heater" => 6,
            "gas-water-heater" => 7,
            "watchman-stand" => 8,
            "cistern" => 9,
            "white-clothes-closet" => 10,
            "equiped-kitchen" => 11,
            "dinning-room" => 12,
            "antisismic-construction" => 13,
            "plaster-cornices" => 14,
            "machine-room" => 15,
            "utility-room-bathroom" => 16,
            "counter-top" => 17,
            "pantry" => 18,
            "trash-chute" => 19,
            "principal-room-bathroom" => 20,
            "family-room" => 21,
            "common-gas" => 22,
            "imported-fittings" => 23,
            "intercom" => 24,
            "jacuzzi" => 25,
            "garden" => 26,
            "kiosk" => 27,
            "lobby" => 28,
            "double-garage" => 29,
            "half-bathroom" => 30,
            "receiver" => 31,
            "extra-parkings" => 32,
            "patio-with-garden" => 33,
            "pool" => 34,
            "marmol-floors" => 35,
            "electric-plant" => 36,
            "mahogany-terminations" => 37,
            "terrace" => 38,
            "pre-installed-services" => 39,
            "granite-countertops" => 40,
            "electric-gate" => 41,
            "walk-in-closet" => 42
        )
    );
    public static $environment_vars = array(
        'user_photos_dir_path' => '/images/userPhotos/',
        'user_photos_thumbs_dir_path' => '/images/userPhotosThumbs/',
        'properties_photos_dir_path' => '/images/propertiesPhotos/',
        'properties_photos_thumbs_dir_path' => '/images/propertiesPhotosThumbs/'
    );

}

?>
